version: '3.8'

services:
  flink-worker:
    image: flink-nexmark:latest
    container_name: flink-worker-${NODE_ID}
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: 192.168.2.70
        jobmanager.rpc.port: 6123
        taskmanager.host: ${WORKER_IP}
        taskmanager.rpc.port: 6122
        taskmanager.numberOfTaskSlots: 4
        parallelism.default: 9
      - KAFKA_BOOTSTRAP_SERVERS=192.168.2.70:9094
    network_mode: host
    restart: unless-stopped
