version: '3.8'

services:
  flink-jobmanager:
    image: flink-nexmark:latest
    container_name: flink-jobmanager
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: 192.168.2.70
        jobmanager.rpc.port: 6123
        jobmanager.bind-host: 0.0.0.0
        rest.address: 192.168.2.70
        rest.bind-address: 0.0.0.0
        rest.port: 8081
        parallelism.default: 9
        taskmanager.numberOfTaskSlots: 4
      - KAFKA_BOOTSTRAP_SERVERS=192.168.2.70:9094
    network_mode: host
    restart: unless-stopped
